<a href="https://colab.research.google.com/github/disiree31-abel/cs82a-portfolio/blob/main/Module_5_Lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [3]:
cust = pd.read_csv("custdata (1).tsv", sep="\t")
cust.head()

,custid,sex,is.employed,income,marital.stat,health.ins,housing.type,recent.move,num.vehicles,age,state.of.res
0,2068,F,NaN,11300,Married,True,Homeowner free and clear,False,2.0,49.0,Michigan
1,2073,F,NaN,0,Married,True,Rented,True,3.0,40.0,Florida
2,2848,M,True,4500,Never Married,False,Rented,True,3.0,22.0,Georgia
3,5641,M,True,20000,Never Married,False,Occupied with no rent,False,0.0,22.0,New Mexico
4,6369,F,True,12000,Never Married,True,Rented,True,1.0,31.0,Florida

In [4]:
cust.columns

Index(['custid', 'sex', 'is.employed', 'income', 'marital.stat', 'health.ins',
       'housing.type', 'recent.move', 'num.vehicles', 'age', 'state.of.res'],
      dtype='object')

In [5]:
cust[["age", "income", "num.vehicles"]].describe()

               age         income  num.vehicles
count  1000.000000    1000.000000    944.000000
mean     51.699815   53504.771000      1.916314
std      18.863433   65478.065729      1.101618
min       0.000000   -8700.000000      0.000000
25%      38.000000   14600.000000      1.000000
50%      50.000000   35000.000000      2.000000
75%      64.000000   67000.000000      2.000000
max     146.680197  615000.000000      6.000000

In [6]:
before_cleaning = cust[["age", "income", "num.vehicles"]].corr()

before_cleaning

                   age    income  num.vehicles
age           1.000000  0.027429     -0.063666
income        0.027429  1.000000      0.139198
num.vehicles -0.063666  0.139198      1.000000

In [7]:
print("Negative incomes:", (cust["income"] < 0).sum())
print("Impossible ages:", ((cust["age"] < 0) | (cust["age"] > 120)).sum())

Negative incomes: 1
Impossible ages: 7

In [9]:
cust_clean = cust[
    (cust["age"] >= 0) &
    (cust["age"] <= 120) &
    (cust["income"] >= 0)
]

In [10]:
print("Original rows:", len(cust))
print("Cleaned rows:", len(cust_clean))
print("Rows removed:", len(cust) - len(cust_clean))

Original rows: 1000
Cleaned rows: 992
Rows removed: 8

In [11]:
after_cleaning = cust_clean[["age", "income", "num.vehicles"]].corr()

after_cleaning

                   age    income  num.vehicles
age           1.000000  0.017625     -0.071668
income        0.017625  1.000000      0.134271
num.vehicles -0.071668  0.134271      1.000000

In [13]:
before_cleaning

                   age    income  num.vehicles
age           1.000000  0.027429     -0.063666
income        0.027429  1.000000      0.139198
num.vehicles -0.063666  0.139198      1.000000